apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: default
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        service-url:
          # This must contain a list of all Eureka server replicas for registry HA to work correctly
          defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry-0.jhipster-registry.default.svc.cluster.local:8761/eureka/,http://admin:${jhipster.registry.password}@jhipster-registry-1.jhipster-registry.default.svc.cluster.local:8761/eureka/
    jhipster:
      security:
        authentication:
          jwt:
            secret: 6a0c9de218f752789f205b2bd446e6308cf3b653
  #application-prod.yml: |-
  #  configserver:
  #    status: Connected in prod
